apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: "2023241041"
spec:
  type: NodePort
  selector:
    app: lidercom_backend
  ports:
    - port: 5000       # Coincide con el proxy_pass del frontend nginx
      targetPort: 5000
      nodePort: 30005
