from abc import ABC, abstractmethod
from typing import List, Optional
from person.domain.entities.person import Person


class PersonRepositoryPort(ABC):
    @abstractmethod
    async def find_all(self) -> List[Person]: ...

    @abstractmethod
    async def find_by_identification_number(self, identification_number: str) -> Optional[Person]: ...

    @abstractmethod
    async def save(self, data: Person) -> Person: ...

    @abstractmethod
    async def update(self, data: Person) -> Person: ...

    @abstractmethod
    async def save_participant(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def save_employee(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def save_superior(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def save_person_role(self, n_id_person: str, n_id_role: int) -> None: ...

    @abstractmethod
    async def find_role_names_by_person_id(self, n_id_person: str) -> List[str]: ...

    @abstractmethod
    async def find_permissions_by_person_id(self, n_id_person: str) -> List[dict]: ...

    @abstractmethod
    async def save_participant_program(self, n_id_participant: str, n_id_program: str) -> None: ...

    @abstractmethod
    async def find_programs_by_participant_id(self, n_id_person: str) -> List[dict]: ...

    @abstractmethod
    async def find_available_programs(self, n_id_person: str) -> List[dict]: ...

    @abstractmethod
    async def find_by_role_names(self, role_names: List[str]) -> List[dict]: ...

    @abstractmethod
    async def find_employee_programs(self, n_id_employee: str) -> List[dict]: ...

    @abstractmethod
    async def save_employee_program(self, n_id_employee: str, n_id_program: str) -> None: ...

    @abstractmethod
    async def find_program_workshops(self, n_id_program: str) -> List[dict]: ...

    @abstractmethod
    async def delete_person_role(self, n_id_person: str, n_id_role: int) -> None: ...

    @abstractmethod
    async def activate_employee(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def activate_participant(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def activate_superior(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def deactivate_employee(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def deactivate_participant(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def deactivate_superior(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def find_employee_by_id(self, n_id_person: str) -> Optional[object]: ...

    @abstractmethod
    async def find_participant_by_id(self, n_id_person: str) -> Optional[object]: ...

    @abstractmethod
    async def find_superior_by_id(self, n_id_person: str) -> Optional[object]: ...

    @abstractmethod
    async def activate_user(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def deactivate_user(self, n_id_person: str) -> None: ...

    @abstractmethod
    async def find_participants_by_program(self, program_id: str) -> List[dict]: ...

    @abstractmethod
    async def deactivate_participant_program(self, n_id_participant: str, n_id_program: str) -> None: ...

    @abstractmethod
    async def activate_participant_program(self, n_id_participant: str, n_id_program: str) -> None: ...

    @abstractmethod
    async def save_workshop(self, n_id_program: str, c_description: str, c_status: str | None, t_date: str | None) -> dict: ...

    @abstractmethod
    async def update_workshop_status(self, n_id_workshop: str, c_status: str) -> dict | None: ...
