apiVersion: v1
kind: Service
metadata:
  name: psql-service
  namespace: "2023241041"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: lidercom-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-data-pvc
  namespace: "2023241041"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidercom-db
  namespace: "2023241041"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidercom-db
  template:
    metadata:
      labels:
        app: lidercom-db
    spec:
      securityContext:
        fsGroup: 1000 # Requerido por la imagen de Timescale (usuario postgres interno)
      containers:
        - name: postgres
          image: timescale/timescaledb-ha:pg17
          env:
            - name: POSTGRES_DB
              value: "lidercom"
            - name: POSTGRES_USER
              value: "perripopo"
            - name: POSTGRES_PASSWORD
              value: "p3rr1p0p0"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: db-storage
              mountPath: /home/postgres/pgdata # Ruta nativa de Spilo/Timescale
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - perripopo
                - -d
                - lidercom
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - perripopo
                - -d
                - lidercom
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              memory: "256Mi"   # Ajustado para evitar bloqueos por cuota (Pending)
              cpu: "100m"
            limits:
              memory: "1Gi"     # Suficiente RAM para procesamiento y carga del dump
              cpu: "500m"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: psql-data-pvc
