apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: "2023241041"
  labels:
    app: cloudflare-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      hostNetwork: true
      dnsPolicy: Default
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        imagePullPolicy: Always
        args:
        - --config
        - /etc/cloudflared/config.yml
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - eyJhIjoiYjk2ZjE2YTY0ZDc5OTJhN2E2OGJjMmRlYjIxNzc1MTUiLCJ0IjoiZTEzZWVhZTYtMzJiMy00NjNhLThiMDUtYTJhMDk5ZGIyNjk2IiwicyI6Ik9ETTFZbUpqT0RRdE9UQTVaQzAwTkRJeExXSmpPV0l0WTJJMFlURXpOelpoTjJJMiJ9
        volumeMounts:
        - mountPath: /etc/cloudflared/config.yml
          name: tunnel-config
          subPath: config.yml
      volumes:
      - name: tunnel-config
        configMap:
          name: cloudflare-tunnel-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: "2023241041"
data:
  config.yml: |
    ingress:
      - hostname: admin.neravy.us
        service: http://172.16.10.31:30006
      - hostname: lidercom.neravy.us
        service: http://172.16.10.31:30007
      - service: http_status:404
